### ISSUE TITLE
The window is decorated in xfce4

### ISSUE THREAD

**Issue by Misko-2083** [Toqozz/yarn-c#1]
![decor](https://user-images.githubusercontent.com/8826552/111327857-08f91c00-866e-11eb-96c4-cf8e99d3ced1.png)

Setting MOTIF_WM_HINTS undecorates the window.
https://github.com/Toqozz/yarn/pull/2/commits/41a77243180d6696afe4816574725ec0162e4e3d

**Comment by Toqozz** [comment]
Merged.
